env:
  node: true

extends:
  - "eslint:recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:unicorn/recommended"

plugins:
  - "import"
  - "json"

rules:
  "unicorn/prevent-abbreviations": 0
  "import/first": 2
  "import/exports-last": 2
  "import/no-duplicates": 2
  "import/extensions":
    - "error"
    - "ignorePackages"
    - js: "never"
  "import/max-dependencies":
    - "error"
    - max: 10
  "import/no-default-export": 2
  "import/no-unassigned-import": 2
  "no-unused-vars":
    - "error"
